###
#   Database Settings
#   URL de acesso: localhost:8080/h2-console
#   Se a configuracao estiver no Servico Fornedor usar a porta do Fornecedor : http://localhost:8081/h2-console
#
#   Ip do Servico do Fornecedor = 8081
#
#   Nao usar a porta do Config Server que e 8888
#   url: jdbc:h2:mem:example-app;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE 
###
spring:
  datasource:
    url: jdbc:h2:file:~/test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

###
#   H2 Settings
###
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
